dev: tg0
pkt_size: 1500
batch: 64
count: 10
pre_fill: false
layers:
  - type: eth
    src: de:ad:be:ef:00:00
    dst: de:ad:be:ef:00:01
  - type: vlan
    vlan: 1-10
  - type: ip
    src: 192.168.1.1-192.168.1.255
    dst: 192.168.1.2
  - type: udp
    src: 1000-2000
    dst: 4789
  - type: vxlan
    vni: 10000-20000
  - type: eth
    src: ba:be:00:00:00:00
    dst: ba:be:00:00:00:01
  - type: ip
    src: 10.0.0.0-10.0.255.255
    dst: 10.42.0.0
  - type: udp
    src: 10000-20000
    dst: 12345
