dev: tg0
pkt_size: 1500
batch: 64
count: 10
layers:
  - type: eth
    src: de:ad:be:ef:00:00
    dst: de:ad:be:ef:00:01
    proto: ip
  - type: ip
    src: 192.168.1.1-192.168.1.255
    dst: 192.168.1.2
    proto: udp
  - type: udp
    src: 1000-2000
    dst: 5000
